CREATE TABLE `COP4331`.`Users`
(
`ID` INT NOT NULL AUTO_INCREMENT,
`FirstName` VARCHAR(50) NOT NULL DEFAULT '',
`LastName` VARCHAR(50) NOT NULL DEFAULT '',
`Login` VARCHAR(50) NOT NULL DEFAULT '',
`Password` VARCHAR(255) NOT NULL DEFAULT '',
PRIMARY KEY (`ID`),
UNIQUE (`Login`)
) ENGINE = InnoDB;

CREATE TABLE `COP4331`.`Contacts`
(
`ID` INT NOT NULL AUTO_INCREMENT ,
`FirstName` VARCHAR(50) NOT NULL DEFAULT '' ,
`LastName` VARCHAR(50) NOT NULL DEFAULT '' ,
`Phone` VARCHAR(50) NOT NULL DEFAULT '' ,
`Email` VARCHAR(50) NOT NULL DEFAULT '' ,
`UserID` INT NOT NULL DEFAULT '0' ,
`DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`)
) ENGINE = InnoDB;
